//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFLP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int id { get; set; }
        public int consecutivo { get; set; }
        public Nullable<int> reunion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_claseGanado { get; set; }
        public Nullable<int> corral { get; set; }
        public Nullable<int> cabezas { get; set; }
        public Nullable<int> id_sexo { get; set; }
        public Nullable<int> kilos { get; set; }
        public Nullable<int> valorKg { get; set; }
        public Nullable<double> valorTotal { get; set; }
        public Nullable<int> anio { get; set; }
    
        public virtual CLASE CLASE { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
