//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFLP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porcentajes
    {
        public int ID { get; set; }
        public decimal Feria { get; set; }
        public Nullable<decimal> Recibida { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public Nullable<decimal> FondoNal { get; set; }
    }
}
